V 01+F 01
NikitaUhlin/need-for-drive pull request #1
Opened 2021-09-20 07:15 UTC by NikitaUhlin

Реализована задача V-01 "Верстка главной странницы с предложениями компании" и F-01 "Реализация переключаемого слайдера"

2021-09-20 08:36 UTC, chugunovns21 requested changes

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/button/button.js
> +    )
Не очень красиво и не очень читаемо

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/header/header.js
> +}
Почему бы не использовать современный синтаксис и стрелочные функции?

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/mainPage/mainPage.js
> +import useCurrentWidth from "../../utilities/useCurrentWidth";
Обычно порядок такой:
1) Библиотеки
2) Компоненты
3) Картинки/константы
4) Стили

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/mainPage/mainPage.js
> +        </div>
Лучше вынести в отдельный компонент и импортировать сюда

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/mainPage/mainPage.js
> +                {width >= 1024 ? slider : null}
width >= 1024 && slider - прочитай про такую запись, она приятнее тернальника в этом случае

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/header/header.sass
> +.header
А что будет, если тебе еще где-то понадобится использовать такой css класс? Прочитай про css modules

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/sideBar/sideBar.js
> +    }
Прочитай про современный синтаксис: можно записать без { }

2021-09-20 08:36 UTC, chugunovns21 commented on src/components/sideBar/sideBar.js
> +            />
Чем обоснован вынос простой кнопки в отдельный компонент?

2021-09-20 14:49 UTC, NikitaUhlin commented on src/components/button/button.js
> +    )
Исправлено

2021-09-20 14:49 UTC, NikitaUhlin commented on src/components/header/header.js
> +}
Исправлено

2021-09-20 14:49 UTC, NikitaUhlin commented on src/components/mainPage/mainPage.js
> +import useCurrentWidth from "../../utilities/useCurrentWidth";
Исправлено

2021-09-20 14:49 UTC, NikitaUhlin commented on src/components/mainPage/mainPage.js
> +        </div>
Исправлено

2021-09-20 14:49 UTC, NikitaUhlin commented on src/components/mainPage/mainPage.js
> +                {width >= 1024 ? slider : null}
Исправлено

2021-09-20 14:50 UTC, NikitaUhlin commented on src/components/header/header.sass
> +.header
Перевел весь проект на CSS Modules

2021-09-20 14:50 UTC, NikitaUhlin commented on src/components/sideBar/sideBar.js
> +    }
Исправлено

2021-09-20 14:53 UTC, NikitaUhlin commented on src/components/sideBar/sideBar.js
> +            />
Вынос простой кнопки в отдельный компонент обусловлен наличием большого кол-ва стилей этой кнопки. И чтобы не захламлять логикой классов

2021-09-20 17:51 UTC, chugunovns21 requested changes

2021-09-20 17:51 UTC, chugunovns21 commented on src/components/mainPage/slider/slide/slide.js
> +}
Перешли к стрелочным функциям - хорошо. Теперь следующий этап.
Если стрелочная функция в "одну строчку", то вместо 
const func = () => { 
    console.log(123)
}
Можно записать
const func = () => console.log(123).
Тоже самое с компонентами, которые возвращают нам только jsx
const Slide = () => ( <>content</> )

2021-09-20 17:51 UTC, chugunovns21 commented on src/components/ui/sideBar/sideBar.js
> +        </div>
У тебя ide не подсветила ошибку, что пустой тэг? Если нет контента, то делаем так: `</>'

2021-09-20 17:51 UTC, chugunovns21 commented on src/components/ui/sideBar/sideBar.js
> +        <div>
Если нужно обернуть несколько компонентов в один тэг, без дополнительных функций, используй <></>

2021-09-20 17:51 UTC, chugunovns21 commented on src/components/ui/sideBar/hamburgerBtn/hamburgerBtn.js
> +        <div>
Зачем тут div обертка?

2021-09-21 07:32 UTC, NikitaUhlin commented on src/components/mainPage/slider/slide/slide.js
> +}
Исправлено по всему проекту

2021-09-21 07:32 UTC, NikitaUhlin commented on src/components/ui/sideBar/sideBar.js
> +        </div>
Исправлено по всему проекту

2021-09-21 07:32 UTC, NikitaUhlin commented on src/components/ui/sideBar/sideBar.js
> +        <div>
Исправлено по всему проекту

2021-09-21 07:32 UTC, NikitaUhlin commented on src/components/ui/sideBar/hamburgerBtn/hamburgerBtn.js
> +        <div>
Исправлено по всему проекту

2021-09-21 08:53 UTC, merged