V 05+f 06+v 06+f 07
NikitaUhlin/need-for-drive pull request #11
Opened 2021-11-07 15:44 UTC by NikitaUhlin

2021-11-07 16:39 UTC, chugunovns21 requested changes

2021-11-07 16:39 UTC, chugunovns21 commented on src/common/Modal/Modal.js
> +}
Продолжи замечание: синтаксис стрелочных ...

2021-11-07 16:39 UTC, chugunovns21 commented on src/components/OrderPage/OrderPage.js
> +    const onOk = () => {
Название нужно поменять на более адекватное. Например что-то со словом accept

2021-11-07 16:39 UTC, chugunovns21 commented on src/components/OrderPage/OrderPage.js
> +        }
Сделай в отдельном файле функцию утилиту которая будет заполнять заказ, чтобы этого не было в коде компонента

2021-11-07 16:39 UTC, chugunovns21 commented on src/components/PanelInfo/Component/PanelInfo.js
>      })
Глупый компонент, по хорошему, должен содержать только верстку. Есть ли возможность вынести из него всю логику?

2021-11-08 07:30 UTC, NikitaUhlin commented on src/common/Modal/Modal.js
> +}
...функций. Исправлено

2021-11-08 07:31 UTC, NikitaUhlin commented on src/components/OrderPage/OrderPage.js
> +    const onOk = () => {
Исправлено

2021-11-08 07:31 UTC, NikitaUhlin commented on src/components/OrderPage/OrderPage.js
> +        }
Исправлено

2021-11-08 08:48 UTC, NikitaUhlin commented on src/components/PanelInfo/Component/PanelInfo.js
>      })
Исправлено

2021-11-08 12:19 UTC, merged