V 02+f 02
NikitaUhlin/need-for-drive pull request #3
Opened 2021-09-28 10:29 UTC by NikitaUhlin

Реализован 1-й шаг (местоположение) страницы заказа. А именно верстка и переключение вкладок Таб меню.

2021-09-28 15:01 UTC, chugunovns21 requested changes

2021-09-29 12:07 UTC, NikitaUhlin commented on src/components/orderPage/geolocationOrder/geolocationOrder.js
> +            />
Изменена архитектура OrderPage

2021-09-29 12:08 UTC, NikitaUhlin commented on src/store/actions.js
> +};
Исправлено

2021-09-30 16:35 UTC, chugunovns21 requested changes

2021-09-30 16:35 UTC, chugunovns21 commented on src/components/mainPage/mainPage.js
> +import { Link } from "react-router-dom";
Неверный порядок импортов

2021-09-30 16:35 UTC, chugunovns21 commented on src/components/orderPage/orderPage.js
> +    const accessibleTab = useSelector(state => state.accessibleTab)
Прочитай про селекторы в редаксе и начинай их использовать

2021-09-30 16:35 UTC, chugunovns21 commented on src/components/orderPage/orderPage.js
> +    }
Почему не стрелочная функция? Лучше вынести такую функцию в отдельный файл в папке утилс

2021-09-30 16:35 UTC, chugunovns21 commented on src/components/orderPage/Steps/Step1/Step1.js
> +    }
Зачем фигурные скобки?

2021-09-30 16:35 UTC, chugunovns21 commented on src/components/orderPage/Steps/Step1/Step1.js
> +    const pickUp = useSelector(state => state.order.pickUp)
Используй селекторы

2021-09-30 16:35 UTC, chugunovns21 commented on src/components/orderPage/OrderInfo/OrderInfo.js
> +    const buttonText = ["Выбрать модель", "Дополнительно", "Итого", "Заказать"]
Вынеси из компонента. После стилей запиши

2021-10-01 10:23 UTC, NikitaUhlin commented on src/components/orderPage/geolocationOrder/geolocationOrder.js
> +    }
Исправлено

2021-10-01 10:23 UTC, NikitaUhlin commented on src/components/mainPage/mainPage.js
> +import { Link } from "react-router-dom";
Исправлено

2021-10-01 10:23 UTC, NikitaUhlin commented on src/components/orderPage/orderPage.js
> +    const accessibleTab = useSelector(state => state.accessibleTab)
Исправлено

2021-10-01 10:23 UTC, NikitaUhlin commented on src/components/orderPage/orderPage.js
> +    }
Исправлено

2021-10-01 10:23 UTC, NikitaUhlin commented on src/components/orderPage/Steps/Step1/Step1.js
> +    }
Исправлено

2021-10-01 10:23 UTC, NikitaUhlin commented on src/components/orderPage/Steps/Step1/Step1.js
> +    const pickUp = useSelector(state => state.order.pickUp)
Исправлено

2021-10-01 10:24 UTC, NikitaUhlin commented on src/components/orderPage/OrderInfo/OrderInfo.js
> +    const buttonText = ["Выбрать модель", "Дополнительно", "Итого", "Заказать"]
Исправлено

2021-10-01 10:54 UTC, chugunovns21 requested changes

2021-10-01 10:54 UTC, chugunovns21 commented on src/components/mainPage/mainPage.js
> +            <SideBar page="main" />
Хорошее решение)

2021-10-01 11:35 UTC, merged