V 04+f 05
NikitaUhlin/need-for-drive pull request #9
Opened 2021-10-29 18:07 UTC by NikitaUhlin

2021-10-31 18:57 UTC, chugunovns21 requested changes

2021-10-31 18:57 UTC, chugunovns21 commented on src/components/OrderPage/Steps/Step2/Step2.js
> +    }
Синтаксис стрелочных функций

2021-10-31 18:57 UTC, chugunovns21 commented on src/components/OrderPage/Steps/Step3/Step3.js
> +                })}
В прошлом файле сам же исправлял и удалял return)

2021-11-01 11:53 UTC, NikitaUhlin commented on src/components/OrderPage/Steps/Step2/Step2.js
> +    }
Исправлено

2021-11-01 11:53 UTC, NikitaUhlin commented on src/components/OrderPage/Steps/Step3/Step3.js
> +                })}
Исправлено

2021-11-01 12:21 UTC, chugunovns21 requested changes

2021-11-01 12:21 UTC, chugunovns21 commented on src/store/reducers.js
> +            const pointCity = action.payload.data.response.GeoObjectCollection.featureMember[0]
Чтобы не писать тернальники можно использовать такую конструцию:
const x = obj.key || param
если не будет ключа в объекте, запишется param

2021-11-01 13:14 UTC, merged